<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <title>Page Title</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <script>

    //contexto= fazer uma requisição de um série da netflix

    var video = Array()

    video[1]['nome'] = 'Fullmetal Alchemsit'
    video[1]['categoria'] = 'Anime'

    function getVideo(video){
      
      //try= tentar executar um logica
      try {
        //logica
        //http
        console.log(video[0]['nome'])

        //nesse casp estamos fornçando um erro
        //buscando um parametro que não existe 
        //afim de obter uma mensagem de erro
      

      //catch=pegar. Ele pega o erro e trata
      } catch (error) {

        //aqui simulamos uma funcao que envia esse erro para o servidor
        tratarErro(erro)


        console.log('Agora sim podemos tratar esse erro')
        
        //throw= lançamento de exceções, com ele é possivel 
        //fazer com que uma aplicação seja interrompida
        throw new Error('Houve um erro, mas não se preocupe. Estamos trabalhando nisso.')
      
        //executa algo sempre depois do try ou do catch
        //é muito utilizado para redução de linha de código tambem
      }finally{

        console.log('Sempre passa por aqui (try / catch)')
      }
    }

  </script>
</head>
<body>
  
</body>
</html>